In [65]:
import numpy as np

In [66]:
arr = np.random.randint(0,100,50)

In [67]:
arr

array([83, 23, 96, 21, 82, 41,  2,  1, 13, 53, 65, 11, 80, 78, 76, 56, 86,
       17, 72, 34, 17, 30, 37, 81, 28, 55, 35, 48, 26, 76, 25, 69, 48, 98,
       45, 97, 28,  8, 15,  4, 71, 61, 28, 99, 93, 16, 89, 92, 21, 19])

In [68]:
x = arr[0:25]

In [69]:
x

array([83, 23, 96, 21, 82, 41,  2,  1, 13, 53, 65, 11, 80, 78, 76, 56, 86,
       17, 72, 34, 17, 30, 37, 81, 28])

In [70]:
arr1 = x.copy()

In [71]:
arr1.shape

(25,)

In [72]:
y = arr[25:]

In [73]:
arr2 = y.copy()

In [74]:
arr2.shape

(25,)

In [75]:
arr1 = arr1.reshape(5,5)

In [76]:
arr2 = arr2.reshape(5,5)

In [77]:
arr1

array([[83, 23, 96, 21, 82],
       [41,  2,  1, 13, 53],
       [65, 11, 80, 78, 76],
       [56, 86, 17, 72, 34],
       [17, 30, 37, 81, 28]])

In [78]:
arr2

array([[55, 35, 48, 26, 76],
       [25, 69, 48, 98, 45],
       [97, 28,  8, 15,  4],
       [71, 61, 28, 99, 93],
       [16, 89, 92, 21, 19]])